ARG BASE_IMG=php:7.4

FROM $BASE_IMG

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8

# Runtime dependencies
ENV PHPIZE_DEPS \
    autoconf \
    file \
    g++ \
    gcc \
    libc-dev \
    make \
    pkgconf \
    re2c

ENV BUILD_DEPS \
        freetype-dev libjpeg-turbo-dev libpng-dev \
        libwebp-dev libxpm-dev imagemagick-dev \
        libtool \
        icu-dev \
        libxml2-dev \
        gettext-dev \
        enchant-dev aspell-dev \
        tidyhtml-dev \
        libxslt-dev \
        yaml-dev \
        bzip2-dev libzip-dev \
        recode-dev \
        net-snmp-dev \
        postgresql-dev \
        openldap-dev \
        gmp-dev \
        oniguruma-dev

ENV PERSISTENT_DEPS \
        freetype libjpeg-turbo libpng \
        libwebp libxpm imagemagick \
        libltdl \
        icu-libs \
        libxml2 \
        libpq \
        gettext \
        enchant aspell \
        tidyhtml \
        libxslt \
        yaml \
        bzip2 libzip \
        recode \
        net-snmp

ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

RUN apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing gnu-libiconv \
    && apk add --no-cache $PERSISTENT_DEPS \
    && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS $BUILD_DEPS \
    && docker-php-ext-configure gd --with-freetype=/usr/include/ \
                                    --with-jpeg=/usr/include/ \
                                    --with-xpm==/usr/include/ \
                                    --with-webp==/usr/include/ \
    && docker-php-ext-configure intl --enable-intl \
    && docker-php-ext-install -j$(nproc) \
        gd exif \
        ldap \
        bcmath gmp \
        opcache \
        intl \
        iconv \
        mbstring \
        dba \
        mysqli pgsql pdo_mysql pdo_pgsql \
        soap \
        bz2 zip \
        tidy \
        pspell \
        enchant \
        calendar \
        gettext \
        xmlrpc \
        shmop sysvmsg sysvsem sysvshm \
        sockets \
        shmop \
        pcntl \
        xsl \
        snmp \
    # Pecl \
    && pecl channel-update pecl.php.net \
    && pecl install imagick && docker-php-ext-enable imagick \
    && pecl install yaml-2.0.4 && docker-php-ext-enable yaml \
    && apk del .build-deps

CMD ["php-fpm"]
