FROM tkanstantsin/universal-docker-server-php-fpm-alpine:4.0

# Utils
RUN apk add --no-cache \
            bash bash-completion coreutils \
            mc htop \
            nano vim \
            git rsyslog \
            curl wget zip unzip \
    # Fix terminal
    # TODO: check i needed in alpine.
    && echo "export TERM=xterm mc" >> ~/.bashrc \
    \
    # Install ssl cerbot
    # TODO check if works in same way.
    && apk add --no-cache certbot \
    \
    # install sshd
    # TODO: check paths in alpine.
    && apk add --no-cache openssh-server openssh-client \
    && mkdir -p /var/run/sshd \
    #RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key && ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
    && sed -ri 's/PermitRootLogin without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config \
    # Put your own public key at id_rsa.pub for key-based login.
    && mkdir -p /root/.ssh && chmod 700 /root/.ssh \
    && touch /root/.ssh/authorized_keys \
    \
    # Install composer
    && curl -sS https://getcomposer.org/installer -o composer-setup.php \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    \
    # Install supervisord
    && apk add --no-cache supervisor \
    && mkdir -p /var/log/supervisord

# TODO: check path to crond - changed in alpine.

CMD ["supervisord", "-n"]
