FROM tkanstantsin/universal-docker-server-php-fpm-alpine:4.5-php7.3

# Utils
RUN apk add --no-cache --virtual .build-deps \
            git \
    \
    && apk add --no-cache \
            bash coreutils \
            mc htop curl \
            rsyslog \
    # Fix terminal
    && echo "export TERM=xterm mc" >> ~/.bashrc \
    \
    # Cerbot
    # TODO check if works in same way.
    && apk add --no-cache certbot \
    \
    # Supervisor
    && apk add --no-cache python3 \
        && python3 -m ensurepip \
        && rm -r /usr/lib/python*/ensurepip \
        && pip3 install --upgrade pip setuptools \
        && if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi \
        && if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi \
        && rm -r /root/.cache \
    # Install supervisord
    && pip install git+https://github.com/Supervisor/supervisor \
    && mkdir -p /var/log/supervisord \
    \
    && apk del .build-deps

# TODO: check path to crond - changed in alpine.

CMD ["supervisord", "-n"]
