FROM registry.kakadu.space/web/mypets:4.0-php-fpm

# Utils
RUN apk add --no-cache \
            bash bash-completion coreutils \
            mc htop bash-completion \
            nano vim \
            git rsyslog \
            curl wget zip unzip \
    # Fix terminal
    # todo: check i needed in alpine.
    && echo "export TERM=xterm mc" >> ~/.bashrc \
    \
    # Install ssl cerbot
    # todo check if works in same way.
    && apk add --no-cache certbot \
    \
    # install sshd
    # todo: check paths in alpine.
    && apk add --no-cache openssh-server openssh-client \
    && mkdir -p /var/run/sshd \
    #RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key && ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
    && sed -ri 's/PermitRootLogin without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config \
    # Put your own public key at id_rsa.pub for key-based login.
    && mkdir -p /root/.ssh && chmod 700 /root/.ssh \
    && touch /root/.ssh/authorized_keys \
    \
    # Install composer
    && curl -sS https://getcomposer.org/installer -o composer-setup.php \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    \
    # MySQL client
    # todo: check if fully compatible with mysql-client-5.7. There mariadb-client-10 used.
    && apk add --no-cache mysql-client \
    \
    # Install supervisord
    && apk add --no-cache supervisor \
    # todo: check paths.
    && mkdir -p /var/log/supervisord

CMD ["supervisord", "-n"]
