version: '2'

services:
  server:
    hostname: server
    image: ${SERVER_REPOSITORY}
    container_name: ${COMPOSE_PROJECT_NAME}_server
    expose:
      - ${DEBUG_PORT}
    environment:
      ENV_PATH: ${PROJECT_DOCKER_FOLDER_CONTAINER}/.env
    labels:
      project: ${PROJECT_NAME}
      container: ${COMPOSE_PROJECT_NAME}_server
    volumes:
      - ${PROJECT_ROOT}:${PROJECT_ROOT_CONTAINER}
      - ${PACKAGE_DOCKER_FOLDER}:${PACKAGE_DOCKER_FOLDER_CONTAINER}
      - ${PACKAGE_DOCKER_FOLDER}/scripts:/scripts
      - ${PROJECT_DOCKER_FOLDER}/letsencrypt/${PROJECT_ENVIRONMENT}:/etc/letsencrypt
      # cron
      - ${PACKAGE_DOCKER_FOLDER}/pam/pam.d/cron:/etc/pam.d/cron
      - ${PROJECT_DOCKER_FOLDER}/cron/server/logs:/var/log/cron
      # php
      - ${PACKAGE_DOCKER_FOLDER}/php/php.ini-production:/usr/local/etc/php/php.ini
      - ${PACKAGE_DOCKER_FOLDER}/php/pool.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      # enable for dev only
      #- ${PACKAGE_DOCKER_FOLDER}/php/mods-available/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ${PROJECT_DOCKER_FOLDER}/php/logs:/var/log/php-fpm/
      # supervisor
      - ${PACKAGE_DOCKER_FOLDER}/supervisord/supervisord.conf:/etc/supervisord.conf
      - ${PROJECT_DOCKER_FOLDER}/supervisord/server/logs:/var/log/supervisord
      - ${PACKAGE_DOCKER_FOLDER}/supervisord/server/services:/etc/supervisor/conf.d
    working_dir: ${PROJECT_ROOT_CONTAINER}
    networks:
      common:
        aliases:
          - server

networks:
  common:
    driver: bridge